# ============================================================================
# 目录配置
# ============================================================================

[paths]

# 数据根目录
data_dir = "data"


# ============================================================================
# 特征值 Feature 相关配置
# ============================================================================

[feature]

# Feature 定义规范版本
definition_version = "1.0"

# Feature 实现代码版本
code_version = "1.0.0"

# Feature 元数据格式版本
metadata_version = "1.0"

# Draw-level / Number-level 特征使用的滚动窗口
rolling_windows = [10, 20, 50, 100]

# Number-level 号码频率特征使用的历史窗口
frequency_windows = [10, 20, 50, 100]

# Number-level 重复历史特征使用的历史窗口
repeat_windows = [10, 20, 50]


# ============================================================================
# 规则
# ============================================================================

[rules]


# ---------------------------------------------------------------------------
# 大乐透奖级规则版本配置
# ---------------------------------------------------------------------------
#
# 大乐透奖级规则存在版本变化。
# 此处只有在大乐透官方更改奖级规则时，进行配置追加，将最后一项 end_issue = 99999 更改为截至期号，将追加项 end_issue 更改为 99999。
#
# 每个规则版本对应一个明确的开奖期号区间。
#
# name:
#   名称，不能重复，按照格式依次类推。
#
# start_issue:
#   起始期号，包含该期。
#
# end_issue:
#   结束期号，包含该期。
#
# 期号区间应保持连续且互不重叠。
#

[[rules.rule_versions]]
name = "v1"
start_issue = 1
end_issue = 14051

[[rules.rule_versions]]
name = "v2"
start_issue = 14052
end_issue = 19018

[[rules.rule_versions]]
name = "v3"
start_issue = 19019
end_issue = 26013

[[rules.rule_versions]]
name = "v4"
start_issue = 26014
end_issue = 99999


# ---------------------------------------------------------------------------
# 派奖活动
# ---------------------------------------------------------------------------
#
# 大乐透在特定时间段内，额外拿出一笔钱加到奖池里，让中奖者能分到更多奖金。
# 此处只有在大乐透官方开启新的派奖活动时，进行配置追加。
# FIXME 如果当前正处于派奖活动，但是并未结束，不知道结束期号，如何处理
#
# 每个派奖活动对应一个明确的派奖期号区间。
#
# name:
#   名称，不能重复，按照格式（bonus_<年份>_<开始期号>_<结束期号>）依次类推。
#
# start_issue:
#   活动开始期号，包含该期。
#
# end_issue:
#   活动结束期号，包含该期。
#
# 期号区间应保持连续且互不重叠。
#

[[rules.bonus_campaigns]]
name = "bonus_2021_21039_21059"
start_issue = 21039
end_issue = 21059

[[rules.bonus_campaigns]]
name = "bonus_2022_22040_22068"
start_issue = 22040
end_issue = 22068

[[rules.bonus_campaigns]]
name = "bonus_2023_23039_23059"
start_issue = 23039
end_issue = 23059

[[rules.bonus_campaigns]]
name = "bonus_2024_24030_24062"
start_issue = 24030
end_issue = 24062

[[rules.bonus_campaigns]]
name = "bonus_2025_25038_25057"
start_issue = 25038
end_issue = 25057

[[rules.bonus_campaigns]]
name = "bonus_2026_26050_26066"
start_issue = 26050
end_issue = 26066
