[project]
name = "lottery-not-quite-random"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "henryau", email = "henryau53@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
lottery-not-quite-random = "lottery_not_quite_random:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
